services:
  - type: web
    name: lingopet-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:5000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0