DOG_LABEL_TYPE = {
    'The dog appears to be unwell, showing signs of discomfort and possibly in need of veterinary care. Its body language suggests lethargy and unease.': 'sick',
    'Your dog is playfully searching for someone to engage with, exhibiting excitement and a desire for fun activities, wagging its tail energetically.': 'playful',
    'The dog is sniffing around intently, indicating it senses something unusual or potentially dangerous in its environment, alerting you to remain vigilant.': 'alert',
    'A potential danger is approaching, and the dog is on high alert, barking or growling to warn you to be cautious and attentive to its surroundings.': 'warning',
    'There is a perceived threat nearby, and the dog is trying to communicate its concern through barking or other vocalizations, urging you to pay attention.': 'warning',
    'Your dog is in a playful mood, exhibiting joyful behavior and inviting you to participate in fun activities, possibly with a toy or during playtime.': 'playful',
    'The dog is barking excitedly, expressing pure joy and enthusiasm, perhaps in response to a favorite activity or seeing a familiar person.': 'excited',
    'Your dog is alerting you to a potential danger nearby, using its keen senses to identify something unusual in the environment, urging caution.': 'alert',
    'Your dog is basking in the sun, enjoying the warmth and beauty of the outdoors, displaying a relaxed and content demeanor.': 'relaxed',
    'The dog is amusing itself by chasing its own tail in circles, showcasing its playful spirit and delight in simple joys.': 'playful',
    'Your dog is exhibiting aggressive behavior, growling and barking, indicating extreme anger and a readiness to defend itself or its territory.': 'angry',
    'The dog is alerting you to something it perceives as significant or unusual, using vocalizations to communicate its concerns or observations.': 'alert',
    'Your dog is resting peacefully, fully relaxed and enjoying a calm moment, perhaps after a day filled with play and exploration.': 'relaxed',
    'Your dog is curiously exploring its surroundings, attentively observing everything, showcasing its inquisitive nature and desire to learn.': 'curious',
    'The dog is barking and growling aggressively, possibly feeling threatened or protective, displaying a strong defensive stance.': 'angry',
    'Your dog is eagerly waiting for a walk or outdoor adventure, showing excitement and anticipation, ready to explore new environments.': 'excited',
    'Your dog is barking at a stranger, signaling its alertness and protectiveness, demonstrating a keen awareness of its surroundings.': 'protective',
    'The dog is whining for attention, indicating a strong desire for interaction or play, showcasing its need for companionship.': 'needy',
    'Your dog is digging in the yard, possibly searching for something interesting or simply enjoying the tactile experience of the soil.': 'curious',
    'Your dog is having a fantastic time playing fetch with a ball, exhibiting joy and enthusiasm in this interactive game.': 'playful',
    'The dog is sniffing around excitedly, exploring new scents and surroundings, showcasing its natural curiosity and investigative instincts.': 'curious',
    'Your dog is howling at the moon, expressing its feelings in a melodious way, possibly joining in with other howling dogs in the area.': 'melodious',
    'Your dog is savoring a special treat, enjoying every bite with delight, showcasing its appreciation for tasty rewards.': 'happy',
    'The dog is running in circles, filled with energy and joy, clearly having a blast and reveling in its playful spirit.': 'playful',
    'Your dog is very protective of you, watching closely for any potential threats, displaying vigilance and loyalty.': 'protective',
    'Your dog is exploring a new environment, taking in all the new sights and smells, demonstrating its adventurous spirit.': 'curious',
    'Your dog is barking at a nearby animal, revealing its playful and curious nature, eager to interact with other creatures.': 'playful',
    'Your dog is feeling sleepy, possibly after a long day of play and exploration, showing signs of relaxation and contentment.': 'sleepy',
    'Your dog is enjoying a playful moment with another dog, sharing joy and companionship in their interaction.': 'playful',
    'The dog is watching something intently, focused and curious about its surroundings, displaying a keen interest in its environment.': 'curious',
    'Your dog is relishing a belly rub, enjoying the affection and attention from you, displaying trust and contentment.': 'affectionate',
    'Your dog is feeling a bit shy, perhaps unsure about something in its environment, showing cautious behavior and hesitance.': 'shy',
    'The dog is alert and on guard, ready to react to any potential threats, demonstrating its protective instincts.': 'alert',
    'Your dog is wagging its tail happily, showing excitement and joy, a clear sign of its positive emotional state.': 'happy',
    'Your dog is trying to catch a butterfly, showcasing its playful and curious nature as it engages with the world around it.': 'playful',
    'The dog is barking at the mailman, indicating its protective instincts and desire to guard its territory.': 'protective',
    'Your dog is playing in the water, splashing around and having a fantastic time, clearly enjoying the refreshing experience.': 'playful',
    'Your dog is searching for its favorite toy, eager to play and have fun, displaying its playful enthusiasm.': 'playful',
    'The dog is being very affectionate, showing love and companionship, strengthening the bond with its owner.': 'affectionate',
    'Your dog is panting after an energetic run, indicating it had a great time playing and exercising.': 'tired',
    'Your dog is cozily watching a movie with you, enjoying the shared experience and the warmth of companionship.': 'relaxed',
    'The dog is feeling adventurous, ready to explore new places and experiences, showcasing its lively spirit.': 'adventurous',
    'Your dog is enjoying a car ride, thrilled by the new sights and smells, displaying excitement and curiosity.': 'excited',
    'Your dog is investigating a new scent, exploring its curiosity about the world, eager to uncover new experiences.': 'curious',
    'The dog is barking excitedly at a friend, eager to play and interact, showcasing its friendly demeanor.': 'excited',
    'Your dog is cuddling with you, enjoying the warmth and affection, fostering a loving bond between you.': 'affectionate',
    'Your dog is showing signs of displeasure, perhaps mad at you, with a huff or a glare indicating its feelings.': 'displeased',
    'The dog is barking and whining, expressing excitement and a strong desire for engagement, showcasing its playful nature.': 'excited',
    'The dog is joyfully whining, expressing happiness and eagerness for interaction, radiating positive energy.': 'happy',
    'The dog is whimpering softly, indicating signs of discomfort or a need for attention, reflecting its emotional state.': 'needy',
    'The dog is whimpering gently, seeking comfort or reassurance from its owner, highlighting its vulnerability.': 'needy',
    'The dog is whimpering softly, showing a desire for affection or care, conveying its emotional needs.': 'needy',
    'The dog is alternating between whining and barking, indicating a playful mood, full of energy and enthusiasm.': 'playful',
    'The dog is whimpering affectionately, seeking love and companionship, reflecting its bond with its owner.': 'affectionate',
    'The dog is whining, expressing discomfort or a need for attention, showcasing its sensitivity.': 'needy',
    'The dog is whining, indicating a desire for interaction or care, reflecting its emotional state.': 'needy',
    'The dog is whining softly, expressing a need for companionship, showcasing its affectionate nature.': 'needy',
    'The puppy is whining cutely, seeking attention and affection from its owner, radiating innocence.': 'needy',
    'A soft, plaintive whining sound from a dog, expressing feelings of discomfort or a desire for attention. This sound captures the essence of a dog\'s need for companionship or reassurance, evoking empathy.': 'needy',
    'A high-pitched, heart-wrenching cry from a puppy, conveying innocence and vulnerability. This sound effect is perfect for evoking sympathy and highlighting the emotional needs of young dogs, making it impactful in storytelling.': 'needy',
    'A gentle, sorrowful cry from a dog, suggesting a longing for affection and comfort. This sound captures the emotional bond between dogs and their owners, ideal for scenes requiring a heartfelt touch and connection.': 'needy',
    'A series of whining sounds from a dog, indicating restlessness or a plea for attention. This sound effect effectively portrays a dog\'s emotional state and can be used to enhance narratives involving canine characters, adding depth to storytelling.': 'needy',
    'The sound of a hound flapping its ears, creating a playful and lighthearted atmosphere, often associated with curiosity or excitement, bringing a smile to listeners.': 'playful',
    'The dog is growling aggressively, signaling anger or a warning to potential threats, creating a tense atmosphere that requires attention.': 'angry',
    'The dog is barking loudly in anger, expressing frustration or a desire to defend its territory, showcasing its protective instincts.': 'angry',
    'The dog is alternating between barking and growling, showing heightened aggression and alertness, indicating a serious situation that demands caution.': 'angry',
    'The dog is growling and snarling, indicating serious displeasure or a defensive stance, creating a sense of danger and urgency.': 'angry',
    'A gentle, pleading whimper from a dog, expressing a heartfelt desire for attention and connection. This sound reflects the loyal companionship between dogs and their owners, perfect for moments that highlight emotional ties and affection.': 'needy',
    'The dog emits a deep, angry growl, suggesting it feels threatened or protective, evoking a sense of caution.': 'angry',
    'A soft, yearning whine from a dog want maybe a hug, conveying a deep need for companionship and warmth. This sound captures the affectionate bond between dogs and their owners, ideal for scenes that evoke a sense of love and longing.': 'emotional',
    'The dog growls angrily, demonstrating its readiness to confront any perceived danger, portraying its fierce loyalty.': 'angry',
    'The dog is growling fiercely, indicating strong feelings of anger or territorial defense, enhancing the tension in the environment.': 'angry',
    'Your dog is crying softly, capturing the emotional expressions of dogs, conveying feelings of sadness, loneliness, or distress, evoking empathy from listeners.': 'sad',
    'The dog is barking, a common vocalization for communication or alerting others, showcasing its active engagement with the environment.': 'alert',
    'The dog emits a unique barking sound, resembling a zombie-like quality, adding a spooky effect that can create suspense.': 'spooky',
    'The dog is barking, expressing excitement or alertness to its surroundings, showcasing its lively personality.': 'excited',
    'The sound of a dog barking in an outdoor setting, contributing to a lively ambiance, enhancing the atmosphere of nature.': 'ambient',
    'The dog growls in a funny, upset manner, showcasing a playful yet annoyed attitude, creating a humorous moment.': 'funny',
    'The dog howls melodiously, perhaps in response to sounds or to communicate with others, adding a musical quality to its vocalizations.': 'melodious',
    'The dog alternates between barking and howling, expressing a mix of excitement and alertness, enhancing the emotional depth of its vocalizations.': 'excited',
    'The large dog is barking with a light snarl, indicating a mix of alertness and mild aggression, suggesting it feels protective or threatened, creating a sense of caution.': 'protective',
    'The dog is snarling menacingly, creating a chilling atmosphere that conveys strong aggression and a sense of danger, heightening the tension in the environment.': 'dangerous',
}

CAT_LABEL_TYPE = {
    "the cat is meowing softly, perhaps trying to communicate its needs or desires": "communicative",
    "your cat wants to play with a toy, showing its playful and energetic side": "playful",
    "your cat is meowing happily, indicating contentment and relaxation": "content",
    "a cat is stretching after a nap, preparing its body for some activity": "active",
    "your cat is watching a bird outside with keen interest and curiosity": "curious",
    "your cat is feeling playful and is looking for something fun to do": "playful",
    "the cat is grooming itself, maintaining its cleanliness and appearance": "grooming",
    "your cat is hiding in a box, enjoying a cozy and secure spot to rest": "resting",
    "your cat is chasing a laser pointer, showcasing its hunting instincts": "hunting",
    "the cat is napping in the sun, enjoying warmth and comfort": "relaxed",
    "your cat is curious about its surroundings, exploring everything with interest": "curious",
    "your cat is scratching a post, keeping its claws healthy and marking territory": "territorial",
    "the cat is watching you intently, possibly curious about your actions": "observant",
    "your cat is climbing on furniture, exploring its vertical territory": "exploring",
    "your cat is feeling affectionate, seeking closeness and companionship": "affectionate",
    "the cat is playing with a ball of yarn, enjoying the thrill of the chase": "playful",
    "your cat is staring out the window, observing the world outside with fascination": "curious",
    "your cat is feeling shy around strangers, possibly hiding or keeping its distance": "shy",
    "the cat is nibbling on some treats, savoring the delicious flavors": "eating",
    "your cat is exploring a new room, investigating every nook and cranny": "exploring",
    "your cat is lounging on your lap, enjoying the warmth and affection": "affectionate",
    "the cat is meowing for attention, trying to get you to interact with it": "seeking for attention",
    "your cat is playing with another cat, engaging in social and playful behavior": "social",
    "your cat is looking for a cozy spot to sleep, seeking comfort and warmth": "tired",
    "the cat is watching a toy move, captivated by its movements": "focused",
    "your cat is feeling a bit grumpy, possibly due to a lack of attention or play": "grumpy",
    "your cat is perched on a high shelf, surveying its domain from above": "observant",
    "the cat is pawing at something, either playing or trying to investigate": "curious",
    "your cat is enjoying a nice scratch behind the ears, relishing the affection": "content",
    "your cat is hiding under the bed, seeking a safe haven from the world": "hiding",
    "the cat is playing with a feather toy, showcasing its hunting skills": "hunting",
    "your cat is getting ready to pounce, preparing for an exciting chase": "hunting",
    "your cat is feeling adventurous outdoors, exploring the great outside world": "adventurous",
    "the cat is curling up next to you, enjoying your company and warmth": "affectionate",
    "your cat is watching a video on the screen, intrigued by the moving images": "curious",
    "your cat is chasing its tail, engaging in playful and silly behavior": "playful",
    "the cat is feeling sleepy after a meal, ready for a cozy nap": "tired",
    "your cat is meowing loudly for food, expressing its hunger clearly": "hungry",
    "your cat is investigating a new scent, curious about its surroundings": "curious",
    "the cat is playing hide and seek, enjoying the thrill of the chase": "playful",
    "your cat is sitting in a sunny spot, soaking up the warmth and light": "relaxed",
    "your cat is feeling playful and energetic, ready for some fun activities": "playful",
    "the cat is observing its surroundings carefully, being cautious and aware": "alert",
    "your cat is enjoying a gentle petting, relishing the affection from you": "content",
    "your cat is watching you doing some activity, curious about your actions": "curious",
    "the cat is feeling relaxed and content, enjoying a peaceful moment": "relaxed",
    "your cat is chasing a shadow, engaged in playful antics and fun": "playful",
    "your cat is curiously pawing at a box, investigating what might be inside": "curious",
    "the cat is playfully batting at a string, showcasing its playful instincts": "playful",
    "your cat is sleeping soundly at your feet, enjoying your presence and warmth": "sleeping",
    "your cat is very angry, showing its displeasure and frustration clearly": "angry",
    "your cat is extremely angry and warning you it will attack if provoked": "aggressive",
    "your cat is eating dry food, savoring its meal with satisfaction": "eating",
    "your cat is hungry and wants to eat, making its needs known to you": "hungry",
    "your cat is crying Indicates distress or a need for attention This sound is often high-pitched and can signify hunger, discomfort, or loneliness.": "distressed",
    "your cat sounds sad Indicates feelings of loneliness or distress This vocalization may be soft and mournful, reflecting emotional discomfort.": "sad",
    "your cat is purring Indicates happiness and comfort This sound is typically associated with contentment and relaxation": "content",
    "your cat is purring it might be want to sleep looking for some relaxation and comfort": "sleepy",
    "your cat is hungry Indicates a desire for food This sound may be a persistent meow or vocalization, often accompanied by begging behavior.": "hungry",
    "your cat is begging Indicates eagerness for a meal This sound is typically loud and insistent, signaling that your cat wants immediate attention to be fed.": "hungry",
    "your cat is vocalizing for food Indicates hunger and impatience This sound can vary in pitch and frequency, often repeated until fed.": "hungry",
    "your cat is purring Indicates deep relaxation and contentment This soothing sound often occurs when your cat is comfortable and happy.": "content",
    "your cat is purring while sleeping Indicates peacefulness and comfort This gentle sound signifies that your cat is in a deep, restful state.": "peaceful",
    "your cat is angry Indicates irritation or displeasure This sound may include hissing or growling, signaling that your cat feels threatened or annoyed.": "angry",
    "your cat is very angry Indicates extreme frustration or aggression This vocalization is often loud and aggressive, warning others to stay away.": "aggressive",
    "your cat is furious Indicates heightened aggression and distress This sound can include intense growling or yowling, showing that your cat is extremely upset.": "aggressive",
    "the cat is hissing loudly, making it clear that it feels threatened and wants to be left alone": "threatened",
    "your cat is swatting at you with its paw, indicating its irritation and frustration": "irritated",
    "this cat is arching its back and puffing up its fur, a classic sign of an angry feline": "defensive",
    "the cat is growling softly, warning you that it is not in a friendly mood": "warning",
    "your cat is staring at you with narrowed eyes, showing its displeasure and annoyance": "displeased",
    "this cat is scratching furiously at the furniture, expressing its anger at being ignored": "frustrated",
    "the cat is meowing loudly and insistently, clearly upset about something": "upset",
    "your cat is retreating to a high place, wanting to escape from a situation that angers it": "avoiding",
    "this cat is flicking its tail rapidly, a sign of agitation and annoyance": "agitated",
    "the cat is refusing to engage, turning its back on you to show its displeasure": "ignoring",
    "the cat is hissing defensively, warning others to stay away from its territory": "defensive",
    "your cat is arching its back and puffing up its fur, trying to appear larger and more intimidating": "intimidating",
    "this cat is crouching low, preparing to defend itself against a perceived threat": "defensive",
    "the cat is swatting at an intruder, using its claws to assert dominance and protect itself": "protective",
    "your cat is growling softly, signaling that it feels threatened and is ready to defend itself": "threatened",
    "this cat is staring intently at a potential threat, assessing whether to flee or fight": "alert",
    "the cat is retreating to a safe spot, indicating it feels vulnerable and needs to protect itself": "retreating",
    "your cat is making defensive movements, ready to pounce if it feels cornered": "defensive",
    "this cat is showing its claws, a clear indication that it is prepared to defend itself if necessary": "threatening",
    "the cat is vocalizing loudly, trying to scare off any perceived threats from its space": "warning",
    "the cats are growling at each other, indicating a confrontation is about to escalate": "fighting",
    "your cat is swatting aggressively, engaging in a physical altercation with another cat": "aggressive",
    "this cat is hissing loudly, warning its opponent to back off before things get serious": "warning",
    "the cats are chasing each other, playfully fighting but with a hint of aggression": "playing",
    "your cat is pinned down, showing signs of submission while defending itself": "submissive",
    "this cat is leaping at its opponent, ready to engage in a fierce battle": "attacking",
    "the cats are entangled in a tussle, with claws out and fur flying": "fighting",
    "your cat is vocalizing aggressively, expressing its intent to fight for dominance": "aggressive",
    "this cat is retreating momentarily, planning its next move in the ongoing fight": "retreating",
    "the cats are engaging in a standoff, staring each other down before deciding to fight or flee": "confrontational",
    "the cat is purring contentedly, indicating it feels safe and happy in its environment": "content",
    "your cat is playfully chasing a toy, full of energy and joy during playtime": "playful",
    "this cat is kneading with its paws, a sign of comfort and happiness while resting": "content",
    "the cat is rolling on its back, inviting affection and showing its playful side": "playful",
    "your cat is meowing cheerfully, expressing excitement for attention or play": "happy",
    "this cat is grooming itself, a sign of relaxation and contentment in its space": "grooming",
    "the cat is happily perched by the window, enjoying the sights and sounds outside": "relaxed",
    "your cat is playfully batting at a feather toy, showcasing its playful and joyful nature": "playful",
    "this cat is curling up next to you, seeking warmth and companionship with a happy demeanor": "affectionate",
    "the cat is energetically exploring its surroundings, filled with curiosity and excitement": "exploring",
    "the cat is stalking quietly, demonstrating its keen focus and stealthiness while hunting": "hunting",
    "your cat is crouched low, preparing to pounce on an unsuspecting target": "hunting",
    "this cat is intently watching a moving object, fully engaged in the hunt": "focused",
    "the cat is making slow, deliberate movements, showcasing its patience and strategy in hunting": "stalking",
    "your cat is playfully batting at a toy, mimicking the motions of catching prey": "playing",
    "this cat is suddenly leaping forward, demonstrating its agility and precision in the hunt": "pouncing",
    "the cat is sniffing the ground, searching for scents that indicate potential prey nearby": "exploring",
    "your cat is hiding behind furniture, waiting for the perfect moment to ambush": "hiding",
    "this cat is chasing after a laser pointer, showcasing its instinctive hunting behavior": "hunting",
    "the cat is proudly presenting its catch, a sign of successful hunting and play": "proud",
    "the male cat is vocalizing loudly, signaling his presence to attract a female": "mating",
    "your female cat is yowling, indicating she is in heat and ready to mate": "mating",
    "this male cat is marking its territory with scent, showcasing dominance and readiness to mate": "territorial",
    "the cats are engaging in playful behavior, a precursor to mating rituals": "playful",
    "your female cat is rolling on the ground, displaying behavior that signals her receptiveness": "mating",
    "this male cat is following the female closely, demonstrating interest and pursuit": "pursuing",
    "the cats are grooming each other, a sign of affection and bonding before mating": "bonding",
    "your male cat is engaging in courtship displays, such as puffing up and showing off": "courting",
    "this female cat is arching her back, a common posture during mating behavior": "mating",
    "the cats are mating, a natural behavior occurring during the breeding season": "mating",
    "the mother cat is softly meowing, calling her kittens to her side": "nurturing",
    "your cat is purring gently, reassuring her kittens and inviting them to cuddle": "nurturing",
    "this mother cat is chirping, a sound that encourages her kittens to come closer": "calling",
    "the mother cat is vocalizing insistently, signaling her kittens to return to safety": "protective",
    "your cat is licking her kittens, reinforcing her bond and nurturing behavior": "grooming",
    "this mother cat is calling out with a series of soft trills, guiding her kittens during play": "nurturing",
    "the mother cat is making a low, comforting sound, helping her kittens feel secure": "comforting",
    "your cat is responding to her kittens' cries, demonstrating her attentiveness and care": "attentive",
    "this mother cat is leading her kittens to food, using gentle calls to guide them": "nurturing",
    "the mother cat is communicating with her kittens through a series of soft, melodic sounds": "nurturing",
    "the cat is yowling loudly, indicating distress and discomfort from pain": "pain",
    "your cat is growling softly, a sign of irritation or pain when touched": "pain",
    "this cat is hiding in a corner, showing signs of fear and withdrawal due to pain": "afraid",
    "the cat is limping, indicating possible injury or pain in its leg": "injured",
    "your cat is vocalizing intermittently, expressing discomfort or pain during movement": "discomfort",
    "this cat is excessively grooming a specific area, a behavior often associated with pain or irritation": "irritated",
    "the cat is refusing to eat, a common sign of pain or illness affecting its appetite": "sick",
    "your cat is showing signs of agitation, such as tail flicking, indicating discomfort or pain": "distressed",
    "this cat is meowing softly while being handled, suggesting it is in pain or discomfort": "pain",
    "the cat is hiding its face, a behavior that can indicate distress or pain from an injury": "distressed",
    "the cat is softly purring while curled up in a cozy spot, indicating deep relaxation": "relaxed",
    "your cat is stretched out comfortably on a sunny windowsill, enjoying the warmth": "relaxed",
    "this cat is dozing lightly, occasionally twitching its paws in a dream state": "sleeping",
    "the cat is lying on its back with paws in the air, a sign of complete trust and comfort": "relaxed",
    "your cat is resting with its eyes half-closed, enjoying a peaceful moment": "relaxed",
    "this cat is nestled in a soft blanket, showcasing its contentment and coziness": "cozy",
    "the cat is resting on a perch, keeping a watchful eye while still appearing relaxed": "resting",
    "your cat is softly kneading a surface, a comforting behavior often seen during rest": "content",
    "this cat is resting beside you, seeking companionship and warmth while relaxing": "affectionate",
    "the cat is breathing slowly and evenly, indicating a deep and restful sleep": "sleeping",
    "the cat is hissing loudly, signaling a clear warning to back off": "warning",
    "your cat is growling lowly, indicating it feels threatened and is ready to defend itself": "warning",
    "this cat is arching its back and puffing up, displaying aggression as a warning sign": "threatening",
    "the cat is staring intently with dilated pupils, a sign of alertness and potential aggression": "alert",
    "your cat is swatting at the air, warning others to keep their distance": "warning",
    "this cat is making short, aggressive meows, expressing irritation or discomfort": "angry",
    "the cat is backing away slowly, indicating it feels threatened and is warning others": "cautious",
    "your cat is flicking its tail rapidly, a common sign of agitation and a warning signal": "agitated",
    "this cat is crouching low with ears back, preparing to defend itself if necessary": "defensive",
    "the cat is vocalizing in a sharp tone, alerting others to a perceived danger or threat": "warning"
}
