DOG_LABEL_TYPE = {
    'The dog appears to be unwell, showing signs of discomfort and possibly in need of veterinary care. Its body language suggests lethargy and unease.': 'sick',
    'Your dog is playfully searching for someone to engage with, exhibiting excitement and a desire for fun activities, wagging its tail energetically.': 'playful',
    'The dog is sniffing around intently, indicating it senses something unusual or potentially dangerous in its environment, alerting you to remain vigilant.': 'alert',
    'A potential danger is approaching, and the dog is on high alert, barking or growling to warn you to be cautious and attentive to its surroundings.': 'warning',
    'There is a perceived threat nearby, and the dog is trying to communicate its concern through barking or other vocalizations, urging you to pay attention.': 'warning',
    'Your dog is in a playful mood, exhibiting joyful behavior and inviting you to participate in fun activities, possibly with a toy or during playtime.': 'playful',
    'The dog is barking excitedly, expressing pure joy and enthusiasm, perhaps in response to a favorite activity or seeing a familiar person.': 'excited',
    'Your dog is alerting you to a potential danger nearby, using its keen senses to identify something unusual in the environment, urging caution.': 'alert',
    'Your dog is basking in the sun, enjoying the warmth and beauty of the outdoors, displaying a relaxed and content demeanor.': 'relaxed',
    'The dog is amusing itself by chasing its own tail in circles, showcasing its playful spirit and delight in simple joys.': 'playful',
    'Your dog is exhibiting aggressive behavior, growling and barking, indicating extreme anger and a readiness to defend itself or its territory.': 'angry',
    'The dog is alerting you to something it perceives as significant or unusual, using vocalizations to communicate its concerns or observations.': 'alert',
    'Your dog is resting peacefully, fully relaxed and enjoying a calm moment, perhaps after a day filled with play and exploration.': 'relaxed',
    'Your dog is curiously exploring its surroundings, attentively observing everything, showcasing its inquisitive nature and desire to learn.': 'curious',
    'The dog is barking and growling aggressively, possibly feeling threatened or protective, displaying a strong defensive stance.': 'angry',
    'Your dog is eagerly waiting for a walk or outdoor adventure, showing excitement and anticipation, ready to explore new environments.': 'excited',
    'Your dog is barking at a stranger, signaling its alertness and protectiveness, demonstrating a keen awareness of its surroundings.': 'protective',
    'The dog is whining for attention, indicating a strong desire for interaction or play, showcasing its need for companionship.': 'needy',
    'Your dog is digging in the yard, possibly searching for something interesting or simply enjoying the tactile experience of the soil.': 'curious',
    'Your dog is having a fantastic time playing fetch with a ball, exhibiting joy and enthusiasm in this interactive game.': 'playful',
    'The dog is sniffing around excitedly, exploring new scents and surroundings, showcasing its natural curiosity and investigative instincts.': 'curious',
    'Your dog is howling at the moon, expressing its feelings in a melodious way, possibly joining in with other howling dogs in the area.': 'melodious',
    'Your dog is savoring a special treat, enjoying every bite with delight, showcasing its appreciation for tasty rewards.': 'happy',
    'The dog is running in circles, filled with energy and joy, clearly having a blast and reveling in its playful spirit.': 'playful',
    'Your dog is very protective of you, watching closely for any potential threats, displaying vigilance and loyalty.': 'protective',
    'Your dog is exploring a new environment, taking in all the new sights and smells, demonstrating its adventurous spirit.': 'curious',
    'Your dog is barking at a nearby animal, revealing its playful and curious nature, eager to interact with other creatures.': 'playful',
    'Your dog is feeling sleepy, possibly after a long day of play and exploration, showing signs of relaxation and contentment.': 'sleepy',
    'Your dog is enjoying a playful moment with another dog, sharing joy and companionship in their interaction.': 'playful',
    'The dog is watching something intently, focused and curious about its surroundings, displaying a keen interest in its environment.': 'curious',
    'Your dog is relishing a belly rub, enjoying the affection and attention from you, displaying trust and contentment.': 'affectionate',
    'Your dog is feeling a bit shy, perhaps unsure about something in its environment, showing cautious behavior and hesitance.': 'shy',
    'The dog is alert and on guard, ready to react to any potential threats, demonstrating its protective instincts.': 'alert',
    'Your dog is wagging its tail happily, showing excitement and joy, a clear sign of its positive emotional state.': 'happy',
    'Your dog is trying to catch a butterfly, showcasing its playful and curious nature as it engages with the world around it.': 'playful',
    'The dog is barking at the mailman, indicating its protective instincts and desire to guard its territory.': 'protective',
    'Your dog is playing in the water, splashing around and having a fantastic time, clearly enjoying the refreshing experience.': 'playful',
    'Your dog is searching for its favorite toy, eager to play and have fun, displaying its playful enthusiasm.': 'playful',
    'The dog is being very affectionate, showing love and companionship, strengthening the bond with its owner.': 'affectionate',
    'Your dog is panting after an energetic run, indicating it had a great time playing and exercising.': 'tired',
    'Your dog is cozily watching a movie with you, enjoying the shared experience and the warmth of companionship.': 'relaxed',
    'The dog is feeling adventurous, ready to explore new places and experiences, showcasing its lively spirit.': 'adventurous',
    'Your dog is enjoying a car ride, thrilled by the new sights and smells, displaying excitement and curiosity.': 'excited',
    'Your dog is investigating a new scent, exploring its curiosity about the world, eager to uncover new experiences.': 'curious',
    'The dog is barking excitedly at a friend, eager to play and interact, showcasing its friendly demeanor.': 'excited',
    'Your dog is cuddling with you, enjoying the warmth and affection, fostering a loving bond between you.': 'affectionate',
    'Your dog is showing signs of displeasure, perhaps mad at you, with a huff or a glare indicating its feelings.': 'displeased',
    'The dog is barking and whining, expressing excitement and a strong desire for engagement, showcasing its playful nature.': 'excited',
    'The dog is joyfully whining, expressing happiness and eagerness for interaction, radiating positive energy.': 'happy',
    'The dog is whimpering softly, indicating signs of discomfort or a need for attention, reflecting its emotional state.': 'needy',
    'The dog is whimpering gently, seeking comfort or reassurance from its owner, highlighting its vulnerability.': 'needy',
    'The dog is whimpering softly, showing a desire for affection or care, conveying its emotional needs.': 'needy',
    'The dog is alternating between whining and barking, indicating a playful mood, full of energy and enthusiasm.': 'playful',
    'The dog is whimpering affectionately, seeking love and companionship, reflecting its bond with its owner.': 'affectionate',
    'The dog is whining, expressing discomfort or a need for attention, showcasing its sensitivity.': 'needy',
    'The dog is whining, indicating a desire for interaction or care, reflecting its emotional state.': 'needy',
    'The dog is whining softly, expressing a need for companionship, showcasing its affectionate nature.': 'needy',
    'The puppy is whining cutely, seeking attention and affection from its owner, radiating innocence.': 'needy',
    'A soft, plaintive whining sound from a dog, expressing feelings of discomfort or a desire for attention. This sound captures the essence of a dog\'s need for companionship or reassurance, evoking empathy.': 'needy',
    'A high-pitched, heart-wrenching cry from a puppy, conveying innocence and vulnerability. This sound effect is perfect for evoking sympathy and highlighting the emotional needs of young dogs, making it impactful in storytelling.': 'needy',
    'A gentle, sorrowful cry from a dog, suggesting a longing for affection and comfort. This sound captures the emotional bond between dogs and their owners, ideal for scenes requiring a heartfelt touch and connection.': 'needy',
    'A series of whining sounds from a dog, indicating restlessness or a plea for attention. This sound effect effectively portrays a dog\'s emotional state and can be used to enhance narratives involving canine characters, adding depth to storytelling.': 'needy',
    'The sound of a hound flapping its ears, creating a playful and lighthearted atmosphere, often associated with curiosity or excitement, bringing a smile to listeners.': 'playful',
    'The dog is growling aggressively, signaling anger or a warning to potential threats, creating a tense atmosphere that requires attention.': 'angry',
    'The dog is barking loudly in anger, expressing frustration or a desire to defend its territory, showcasing its protective instincts.': 'angry',
    'The dog is alternating between barking and growling, showing heightened aggression and alertness, indicating a serious situation that demands caution.': 'angry',
    'The dog is growling and snarling, indicating serious displeasure or a defensive stance, creating a sense of danger and urgency.': 'angry',
    'A gentle, pleading whimper from a dog, expressing a heartfelt desire for attention and connection. This sound reflects the loyal companionship between dogs and their owners, perfect for moments that highlight emotional ties and affection.': 'needy',
    'The dog emits a deep, angry growl, suggesting it feels threatened or protective, evoking a sense of caution.': 'angry',
    'A soft, yearning whine from a dog want maybe a hug, conveying a deep need for companionship and warmth. This sound captures the affectionate bond between dogs and their owners, ideal for scenes that evoke a sense of love and longing.': 'emotional',
    'The dog growls angrily, demonstrating its readiness to confront any perceived danger, portraying its fierce loyalty.': 'angry',
    'The dog is growling fiercely, indicating strong feelings of anger or territorial defense, enhancing the tension in the environment.': 'angry',
    'Your dog is crying softly, capturing the emotional expressions of dogs, conveying feelings of sadness, loneliness, or distress, evoking empathy from listeners.': 'sad',
    'The dog is barking, a common vocalization for communication or alerting others, showcasing its active engagement with the environment.': 'alert',
    'The dog emits a unique barking sound, resembling a zombie-like quality, adding a spooky effect that can create suspense.': 'spooky',
    'The dog is barking, expressing excitement or alertness to its surroundings, showcasing its lively personality.': 'excited',
    'The sound of a dog barking in an outdoor setting, contributing to a lively ambiance, enhancing the atmosphere of nature.': 'ambient',
    'The dog growls in a funny, upset manner, showcasing a playful yet annoyed attitude, creating a humorous moment.': 'funny',
    'The dog howls melodiously, perhaps in response to sounds or to communicate with others, adding a musical quality to its vocalizations.': 'melodious',
    'The dog alternates between barking and howling, expressing a mix of excitement and alertness, enhancing the emotional depth of its vocalizations.': 'excited',
    'The large dog is barking with a light snarl, indicating a mix of alertness and mild aggression, suggesting it feels protective or threatened, creating a sense of caution.': 'protective',
    'The dog is snarling menacingly, creating a chilling atmosphere that conveys strong aggression and a sense of danger, heightening the tension in the environment.': 'dangerous',
}

CAT_LABEL_TYPE = {
    "The cat is meowing softly, perhaps trying to communicate its needs or desires, expressing a gentle call that invites interaction.": "communicative",
    "Your cat wants to play with a toy, showing its playful and energetic side, eagerly engaging in fun activities that stimulate its hunting instincts.": "playful",
    "Your cat is meowing happily, indicating a state of contentment and relaxation, possibly enjoying a cozy spot or your company.": "content",
    "A cat is stretching after a nap, preparing its body for some activity, signaling that it is ready to engage in playful or exploratory behavior.": "active",
    "Your cat is watching a bird outside with keen interest and curiosity, eyes wide and focused, showcasing its natural hunting instincts.": "curious",
    "Your cat is feeling playful and is looking for something fun to do, actively seeking out toys or engaging in playful antics around the house.": "playful",
    "The cat is grooming itself, maintaining its cleanliness and appearance, meticulously licking its fur to ensure it looks its best.": "grooming",
    "Your cat is hiding in a box, enjoying a cozy and secure spot to rest, feeling safe and comfortable in its little hideaway.": "resting",
    "Your cat is chasing a laser pointer, showcasing its hunting instincts, darting and pouncing with excitement and agility.": "hunting",
    "The cat is napping in the sun, enjoying warmth and comfort, blissfully resting in a sunbeam while soaking up the heat.": "relaxed",
    "Your cat is curious about its surroundings, exploring everything with interest, investigating new scents and sights with inquisitive behavior.": "curious",
    "Your cat is scratching a post, keeping its claws healthy and marking territory, engaging in an essential grooming behavior that also relieves stress.": "territorial",
    "The cat is watching you intently, possibly curious about your actions, observing your movements with keen interest and attentiveness.": "observant",
    "Your cat is climbing on furniture, exploring its vertical territory, demonstrating its natural climbing abilities and desire for higher ground.": "exploring",
    "Your cat is feeling affectionate, seeking closeness and companionship, nuzzling against you or purring softly to express its love.": "affectionate",
    "The cat is playing with a ball of yarn, enjoying the thrill of the chase, rolling and batting it around with playful enthusiasm.": "playful",
    "Your cat is staring out the window, observing the world outside with fascination, captivated by the sights and sounds of nature.": "curious",
    "Your cat is feeling shy around strangers, possibly hiding or keeping its distance, exhibiting cautious behavior in unfamiliar situations.": "shy",
    "The cat is nibbling on some treats, savoring the delicious flavors, enjoying its snack time with delight and satisfaction.": "eating",
    "Your cat is exploring a new room, investigating every nook and cranny, showcasing its curious nature and desire to understand its environment.": "exploring",
    "Your cat is lounging on your lap, enjoying the warmth and affection, contentedly resting while basking in your presence.": "affectionate",
    "The cat is meowing for attention, trying to get you to interact with it, expressing its desire for companionship and engagement.": "seeking for attention",
    "Your cat is playing with another cat, engaging in social and playful behavior, fostering bonds through friendly interactions and games.": "social",
    "Your cat is looking for a cozy spot to sleep, seeking comfort and warmth, searching for the perfect place to curl up and doze off.": "tired",
    "The cat is watching a toy move, captivated by its movements, eyes wide and alert as it tracks the toy’s path with keen interest.": "focused",
    "Your cat is feeling a bit grumpy, possibly due to a lack of attention or play, expressing its annoyance through subtle behaviors.": "grumpy",
    "Your cat is perched on a high shelf, surveying its domain from above, enjoying a vantage point that allows it to observe its surroundings.": "observant",
    "The cat is pawing at something, either playing or trying to investigate, displaying its playful curiosity and desire to explore.": "curious",
    "Your cat is enjoying a nice scratch behind the ears, relishing the affection, responding with purrs and contented movements.": "content",
    "Your cat is hiding under the bed, seeking a safe haven from the world, finding comfort in the enclosed space during stressful moments.": "hiding",
    "The cat is playing with a feather toy, showcasing its hunting skills, leaping and darting as it tries to catch the elusive prey.": "hunting",
    "Your cat is getting ready to pounce, preparing for an exciting chase, muscles tense and focused as it anticipates the thrill of the hunt.": "hunting",
    "Your cat is feeling adventurous outdoors, exploring the great outside world, discovering new sights, sounds, and scents with excitement.": "adventurous",
    "The cat is curling up next to you, enjoying your company and warmth, feeling safe and content in your presence.": "affectionate",
    "Your cat is watching a video on the screen, intrigued by the moving images, captivated by the visual stimuli before it.": "curious",
    "Your cat is chasing its tail, engaging in playful and silly behavior, spinning around in circles with joy and excitement.": "playful",
    "The cat is feeling sleepy after a meal, ready for a cozy nap, settling down in a comfortable spot to rest and digest.": "tired",
    "Your cat is meowing loudly for food, expressing its hunger clearly, making its needs known with insistent vocalizations.": "hungry",
    "Your cat is investigating a new scent, curious about its surroundings, sniffing intently to uncover the source of the intriguing aroma.": "curious",
    "The cat is playing hide and seek, enjoying the thrill of the chase, darting in and out of hiding spots during a playful game.": "playful",
    "Your cat is sitting in a sunny spot, soaking up the warmth and light, enjoying the peaceful ambiance of a sunlit afternoon.": "relaxed",
    "Your cat is feeling playful and energetic, ready for some fun activities, eagerly seeking out toys or engaging in playful antics.": "playful",
    "The cat is observing its surroundings carefully, being cautious and aware, displaying a vigilant demeanor as it assesses the environment.": "alert",
    "Your cat is enjoying a gentle petting, relishing the affection from you, responding with soft purrs and relaxed body language.": "content",
    "Your cat is watching you doing some activity, curious about your actions, intrigued by your movements and interactions.": "curious",
    "The cat is feeling relaxed and content, enjoying a peaceful moment, basking in tranquility and comfort in its environment.": "relaxed",
    "Your cat is chasing a shadow, engaged in playful antics and fun, darting around in pursuit of the elusive silhouette.": "playful",
    "Your cat is curiously pawing at a box, investigating what might be inside, driven by its natural curiosity and desire to explore.": "curious",
    "The cat is playfully batting at a string, showcasing its playful instincts, demonstrating agility and enthusiasm in play.": "playful",
    "Your cat is sleeping soundly at your feet, enjoying your presence and warmth, feeling secure and comforted by your proximity.": "sleeping",
    "Your cat is very angry, showing its displeasure and frustration clearly, exhibiting aggressive behaviors to communicate its feelings.": "angry",
    "Your cat is extremely angry and warning you it will attack if provoked, displaying intense vocalizations and body language to signal its distress.": "aggressive",
    "Your cat is eating dry food, savoring its meal with satisfaction, enjoying the crunch and flavors of its favorite kibble.": "eating",
    "Your cat is hungry and wants to eat, making its needs known to you, vocalizing insistently to express its desire for food.": "hungry",
    "Your cat is crying, indicating distress or a need for attention. This sound is often high-pitched and can signify hunger, discomfort, or loneliness.": "distressed",
    "Your cat sounds sad, indicating feelings of loneliness or distress. This vocalization may be soft and mournful, reflecting emotional discomfort.": "sad",
    "Your cat is purring, indicating happiness and comfort. This sound is typically associated with contentment and relaxation, often heard during peaceful moments.": "content",
    "Your cat is purring; it might be wanting to sleep, looking for some relaxation and comfort, settling down in a cozy spot.": "sleepy",
    "Your cat is hungry, indicating a desire for food. This sound may be a persistent meow or vocalization, often accompanied by begging behavior.": "hungry",
    "Your cat is begging, indicating eagerness for a meal. This sound is typically loud and insistent, signaling that your cat wants immediate attention to be fed.": "hungry",
    "Your cat is vocalizing for food, indicating hunger and impatience. This sound can vary in pitch and frequency, often repeated until fed.": "hungry",
    "Your cat is purring, indicating deep relaxation and contentment. This soothing sound often occurs when your cat is comfortable and happy.": "content",
    "Your cat is purring while sleeping, indicating peacefulness and comfort. This gentle sound signifies that your cat is in a deep, restful state.": "peaceful",
    "Your cat is angry, indicating irritation or displeasure. This sound may include hissing or growling, signaling that your cat feels threatened or annoyed.": "angry",
    "Your cat is very angry, indicating extreme frustration or aggression. This vocalization is often loud and aggressive, warning others to stay away.": "aggressive",
    "Your cat is furious, indicating heightened aggression and distress. This sound can include intense growling or yowling, showing that your cat is extremely upset.": "aggressive",
    "The cat is hissing loudly, making it clear that it feels threatened and wants to be left alone, a clear warning to any perceived threats.": "threatened",
    "Your cat is swatting at you with its paw, indicating its irritation and frustration, expressing its displeasure with your actions.": "irritated",
    "This cat is arching its back and puffing up its fur, a classic sign of an angry feline, attempting to make itself appear larger and more intimidating.": "defensive",
    "The cat is growling softly, warning you that it is not in a friendly mood, signaling its discomfort and desire for space.": "warning",
    "Your cat is staring at you with narrowed eyes, showing its displeasure and annoyance, a clear signal that it is unhappy with the situation.": "displeased",
    "This cat is scratching furiously at the furniture, expressing its anger at being ignored, using its claws to vent frustration.": "frustrated",
    "The cat is meowing loudly and insistently, clearly upset about something, demanding attention or expressing its dissatisfaction.": "upset",
    "Your cat is retreating to a high place, wanting to escape from a situation that angers it, seeking safety and a better vantage point.": "avoiding",
    "This cat is flicking its tail rapidly, a sign of agitation and annoyance, indicating that it is feeling disturbed or irritated.": "agitated",
    "The cat is refusing to engage, turning its back on you to show its displeasure, a clear indication of its unwillingness to interact.": "ignoring",
    "The cat is hissing defensively, warning others to stay away from its territory, establishing boundaries to protect itself.": "defensive",
    "Your cat is arching its back and puffing up its fur, trying to appear larger and more intimidating, a common defensive posture.": "intimidating",
    "This cat is crouching low, preparing to defend itself against a perceived threat, ready to react to any potential danger.": "defensive",
    "The cat is swatting at an intruder, using its claws to assert dominance and protect itself, demonstrating its territorial instincts.": "protective",
    "Your cat is growling softly, signaling that it feels threatened and is ready to defend itself, a warning to approach with caution.": "threatened",
    "This cat is staring intently at a potential threat, assessing whether to flee or fight, demonstrating its instinctual caution.": "alert",
    "The cat is retreating to a safe spot, indicating it feels vulnerable and needs to protect itself, seeking refuge from perceived danger.": "retreating",
    "Your cat is making defensive movements, ready to pounce if it feels cornered, showcasing its readiness to react in a tense situation.": "defensive",
    "This cat is showing its claws, a clear indication that it is prepared to defend itself if necessary, signaling its readiness to fight.": "threatening",
    "The cat is vocalizing loudly, trying to scare off any perceived threats from its space, asserting its presence and dominance.": "warning",
    "The cats are growling at each other, indicating a confrontation is about to escalate, tensions rising as they prepare to engage.": "fighting",
    "Your cat is swatting aggressively, engaging in a physical altercation with another cat, demonstrating its assertiveness in the situation.": "aggressive",
    "This cat is hissing loudly, warning its opponent to back off before things get serious, a clear signal of its displeasure.": "warning",
    "The cats are chasing each other, playfully fighting but with a hint of aggression, engaging in a spirited and energetic display.": "playing",
    "Your cat is pinned down, showing signs of submission while defending itself, caught in a vulnerable position yet still cautious.": "submissive",
    "This cat is leaping at its opponent, ready to engage in a fierce battle, showcasing its agility and readiness to defend itself.": "attacking",
    "The cats are entangled in a tussle, with claws out and fur flying, engaged in a playful yet intense confrontation.": "fighting",
    "Your cat is vocalizing aggressively, expressing its intent to fight for dominance, making its feelings known through loud sounds.": "aggressive",
    "This cat is retreating momentarily, planning its next move in the ongoing fight, displaying strategic thinking during the altercation.": "retreating",
    "The cats are engaging in a standoff, staring each other down before deciding to fight or flee, a tense moment filled with anticipation.": "confrontational",
    "The cat is purring contentedly, indicating it feels safe and happy in its environment, enjoying a moment of peace and comfort.": "content",
    "Your cat is playfully chasing a toy, full of energy and joy during playtime, darting around with excitement and enthusiasm.": "playful",
    "This cat is kneading with its paws, a sign of comfort and happiness while resting, displaying a behavior often seen in content felines.": "content",
    "The cat is rolling on its back, inviting affection and showing its playful side, a clear signal that it trusts those around it.": "playful",
    "Your cat is meowing cheerfully, expressing excitement for attention or play, vocalizing its joy and eagerness for interaction.": "happy",
    "This cat is grooming itself, a sign of relaxation and contentment in its space, taking time to care for its appearance.": "grooming",
    "The cat is happily perched by the window, enjoying the sights and sounds outside, captivated by the world beyond the glass.": "relaxed",
    "Your cat is playfully batting at a feather toy, showcasing its playful and joyful nature, fully engaged in the fun of the chase.": "playful",
    "This cat is curling up next to you, seeking warmth and companionship with a happy demeanor, enjoying the bond shared between you.": "affectionate",
    "The cat is energetically exploring its surroundings, filled with curiosity and excitement, eager to discover new things in its environment.": "exploring",
    "The cat is stalking quietly, demonstrating its keen focus and stealthiness while hunting, moving with precision and intent.": "hunting",
    "Your cat is crouched low, preparing to pounce on an unsuspecting target, showcasing its natural hunting instincts in action.": "hunting",
    "This cat is intently watching a moving object, fully engaged in the hunt, eyes locked on its target with unwavering concentration.": "focused",
    "The cat is making slow, deliberate movements, showcasing its patience and strategy in hunting, carefully planning its next move.": "stalking",
    "Your cat is playfully batting at a toy, mimicking the motions of catching prey, engaging in a delightful display of playful behavior.": "playing",
    "This cat is suddenly leaping forward, demonstrating its agility and precision in the hunt, capturing the excitement of the chase.": "pouncing",
    "The cat is sniffing the ground, searching for scents that indicate potential prey nearby, using its keen sense of smell to locate targets.": "exploring",
    "Your cat is hiding behind furniture, waiting for the perfect moment to ambush, showcasing its natural hunting instincts and patience.": "hiding",
    "This cat is chasing after a laser pointer, showcasing its instinctive hunting behavior, eagerly darting and leaping in pursuit of the elusive light.": "hunting",
    "The cat is proudly presenting its catch, a sign of successful hunting and play, displaying its trophy with a sense of accomplishment.": "proud",
    "The male cat is vocalizing loudly, signaling his presence to attract a female, using deep, resonant calls to announce his availability.": "mating",
    "Your female cat is yowling, indicating she is in heat and ready to mate, vocalizing in a way that expresses her readiness for reproduction.": "mating",
    "This male cat is marking its territory with scent, showcasing dominance and readiness to mate, making its presence known to others.": "territorial",
    "The cats are engaging in playful behavior, a precursor to mating rituals, frolicking together in a display of affection and interest.": "playful",
    "Your female cat is rolling on the ground, displaying behavior that signals her receptiveness, inviting attention and interaction from males.": "mating",
    "This male cat is following the female closely, demonstrating interest and pursuit, staying near as he tries to win her affection.": "pursuing",
    "The cats are grooming each other, a sign of affection and bonding before mating, reinforcing their connection through mutual care.": "bonding",
    "Your male cat is engaging in courtship displays, such as puffing up and showing off, trying to impress the female with his size and confidence.": "courting",
    "This female cat is arching her back, a common posture during mating behavior, signaling her readiness and willingness to mate.": "mating",
    "The cats are mating, a natural behavior occurring during the breeding season, engaging in instinctual reproductive activities.": "mating",
    "The mother cat is softly meowing, calling her kittens to her side, using gentle sounds to encourage them to come closer for comfort.": "nurturing",
    "Your cat is purring gently, reassuring her kittens and inviting them to cuddle, creating a nurturing environment for her young.": "nurturing",
    "This mother cat is chirping, a sound that encourages her kittens to come closer, using melodic tones to communicate affection.": "calling",
    "The mother cat is vocalizing insistently, signaling her kittens to return to safety, ensuring they stay close and protected.": "protective",
    "Your cat is licking her kittens, reinforcing her bond and nurturing behavior, grooming them to keep them clean and comfortable.": "grooming",
    "This mother cat is calling out with a series of soft trills, guiding her kittens during play, helping them stay connected and engaged.": "nurturing",
    "The mother cat is making a low, comforting sound, helping her kittens feel secure, providing reassurance through her vocalizations.": "comforting",
    "Your cat is responding to her kittens’ cries, demonstrating her attentiveness and care, ensuring they feel loved and safe.": "attentive",
    "This mother cat is leading her kittens to food, using gentle calls to guide them, teaching them to follow her to nourishment.": "nurturing",
    "The mother cat is communicating with her kittens through a series of soft, melodic sounds, nurturing their bond and encouraging interaction.": "nurturing",
    "The cat is yowling loudly, indicating distress and discomfort from pain, vocalizing its suffering in an urgent manner.": "pain",
    "Your cat is growling softly, a sign of irritation or pain when touched, expressing discomfort and a desire to be left alone.": "pain",
    "This cat is hiding in a corner, showing signs of fear and withdrawal due to pain, seeking safety away from potential threats.": "afraid",
    "The cat is limping, indicating possible injury or pain in its leg, moving cautiously to avoid further discomfort.": "injured",
    "Your cat is vocalizing intermittently, expressing discomfort or pain during movement, signaling that something is wrong.": "discomfort",
    "This cat is excessively grooming a specific area, a behavior often associated with pain or irritation, trying to soothe itself.": "irritated",
    "The cat is refusing to eat, a common sign of pain or illness affecting its appetite, showing a lack of interest in food.": "sick",
    "Your cat is showing signs of agitation, such as tail flicking, indicating discomfort or pain, expressing its distress through body language.": "distressed",
    "This cat is meowing softly while being handled, suggesting it is in pain or discomfort, vocalizing its unease during interaction.": "pain",
    "The cat is hiding its face, a behavior that can indicate distress or pain from an injury, seeking to shield itself from perceived threats.": "distressed",
    "The cat is softly purring while curled up in a cozy spot, indicating deep relaxation, feeling safe and at ease in its environment.": "relaxed",
    "Your cat is stretched out comfortably on a sunny windowsill, enjoying the warmth, basking in the sunlight with a content demeanor.": "relaxed",
    "This cat is dozing lightly, occasionally twitching its paws in a dream state, peacefully resting in a state of blissful slumber.": "sleeping",
    "The cat is lying on its back with paws in the air, a sign of complete trust and comfort, feeling secure enough to expose its belly.": "relaxed",
    "Your cat is resting with its eyes half-closed, enjoying a peaceful moment, drifting in and out of sleep in a relaxed state.": "relaxed",
    "This cat is nestled in a soft blanket, showcasing its contentment and coziness, finding warmth and security in its surroundings.": "cozy",
    "The cat is resting on a perch, keeping a watchful eye while still appearing relaxed, balancing vigilance with comfort.": "resting",
    "Your cat is softly kneading a surface, a comforting behavior often seen during rest, expressing contentment through rhythmic motions.": "content",
    "This cat is resting beside you, seeking companionship and warmth while relaxing, enjoying the bond shared between you.": "affectionate",
    "The cat is breathing slowly and evenly, indicating a deep and restful sleep, fully immersed in a tranquil state of relaxation.": "sleeping",
    "The cat is hissing loudly, signaling a clear warning to back off, expressing its desire for space and safety in a confrontational manner.": "warning",
    "Your cat is growling lowly, indicating it feels threatened and is ready to defend itself, a warning that it is on high alert.": "warning",
    "This cat is arching its back and puffing up, displaying aggression as a warning sign, attempting to intimidate any perceived threats.": "threatening",
    "The cat is staring intently with dilated pupils, a sign of alertness and potential aggression, prepared to react to any disturbances.": "alert",
    "Your cat is swatting at the air, warning others to keep their distance, using its paws to express discomfort or irritation.": "warning",
    "This cat is making short, aggressive meows, expressing irritation or discomfort, vocalizing its displeasure with the situation.": "angry",
    "The cat is backing away slowly, indicating it feels threatened and is warning others, showing a cautious approach to potential danger.": "cautious",
    "Your cat is flicking its tail rapidly, a common sign of agitation and a warning signal, expressing its irritation with quick movements.": "agitated",
    "This cat is crouching low, preparing to defend itself against a perceived threat, signaling its readiness to react to any potential danger.": "defensive",
    "The cat is swatting at an intruder, using its claws to assert dominance and protect itself, showcasing its territorial instincts.": "protective",
}
